export {
  useScreenTargets,
  loadTargets,
  saveTargets,
  getTargetAtPosition,
  getTriggerLabel,
  TRIGGER_LABELS,
  TARGET_PRESETS,
  type ScreenTarget,
  type GestureTrigger,
  type SimpleGestureTrigger,
  type AppCommand,
  type TargetPreset,
  type GetTargetAtPositionOptions,
} from '../vision-unified/hooks/useScreenTargets'
