import type { ICommandDomain, ICommandVerb } from "./i-command.types";

export const I_COMMAND_PREFIXES = [
  "i ",
  "i,",
  "i.",
  "i:",
  "i;",
  "i\n",
];

export const VERB_PATTERNS: Record<ICommandVerb, RegExp[]> = {
  want: [/^want\b/i, /^wanna\b/i],
  need: [/^need\b/i],
  feel: [/^feel\b/i, /^am feeling\b/i],
  think: [/^think\b/i],
  remember: [/^remember\b/i],
  forgot: [/^forgot\b/i, /^forget\b/i, /^lost\b/i],
  pay: [/^pay\b/i, /^send\b/i, /^tip\b/i],
  earn: [/^earn\b/i, /^make money\b/i],
  post: [/^post\b/i, /^publish\b/i],
  make: [/^make\b/i, /^create\b/i, /^edit\b/i],
  protect: [/^protect\b/i, /^prove\b/i, /^copyright\b/i, /^check\b/i],
  go: [/^go\b/i, /^open\b/i, /^take me\b/i],
  plan: [/^plan\b/i, /^organize\b/i, /^schedule\b/i],
  confess: [/^confess\b/i, /^tell you something\b/i],
  save: [/^save\b/i, /^keep\b/i],
  withdraw: [/^withdraw\b/i, /^cash out\b/i, /^cashout\b/i],
  convert: [/^convert\b/i, /^exchange\b/i],
  help: [/^help\b/i],
  unknown: [],
};

export const DOMAIN_KEYWORDS: Record<ICommandDomain, string[]> = {
  private_self: [
    "feel",
    "lost",
    "sad",
    "calm",
    "calm down",
    "scared",
    "afraid",
    "confess",
    "secret",
    "private",
    "trauma",
    "pain",
    "dream",
    "desire",
    "regret",
    "ashamed",
    "anxious",
    "overwhelmed",
    "alone",
    "purpose",
    "become better",
    "clear my head",
  ],

  wallet_economy: [
    "wallet",
    "pay",
    "send",
    "tip",
    "withdraw",
    "cash out",
    "convert",
    "balance",
    "coins",
    "icoin",
    "icoins",
    "money",
    "earn",
    "earnings",
  ],

  feed_content: [
    "feed",
    "watch",
    "content",
    "video",
    "discover",
    "save this",
    "like",
    "share",
  ],

  studio_creation: [
    "studio",
    "edit",
    "make this video",
    "create",
    "caption",
    "cut",
    "filter",
    "export",
    "post this",
    "post",
  ],

  originality_protection: [
    "protect",
    "original",
    "mine",
    "copyright",
    "prove",
    "stolen",
    "ownership",
    "fingerprint",
    "shazam",
  ],

  health: [
    "health",
    "doctor",
    "sleep",
    "workout",
    "trainer",
    "nutrition",
    "diet",
    "food",
    "weight",
    "exercise",
  ],

  career: [
    "job",
    "career",
    "resume",
    "interview",
    "apply",
    "work",
    "skills",
    "hiring",
  ],

  finance: [
    "budget",
    "debt",
    "financial",
    "invest",
    "save money",
    "money",
    "bills",
    "rent",
    "expenses",
  ],

  relationships: [
    "relationship",
    "girlfriend",
    "boyfriend",
    "wife",
    "husband",
    "friend",
    "family",
    "mother",
    "father",
    "breakup",
    "argument",
    "boundary",
    "boundaries",
  ],

  navigation: [
    "open",
    "go to",
    "show me",
    "take me",
    "settings",
    "profile",
    "home",
  ],

  emergency_safety: [
    "kill myself",
    "suicide",
    "hurt myself",
    "hurt someone",
    "emergency",
    "danger",
    "abuse",
    "blood",
    "overdose",
    "can't go on",
  ],

  unknown: [],
};
