export const POPS_EVENT_DROP_REASONS = {
  DUPLICATE_EVENT_ID: "DUPLICATE_EVENT_ID",
  MISSING_REQUIRED_PAYLOAD: "MISSING_REQUIRED_PAYLOAD",
  INVALID_TIMESTAMP: "INVALID_TIMESTAMP",
  EVENT_BEFORE_SESSION_START: "EVENT_BEFORE_SESSION_START",
  EVENT_AFTER_SESSION_END: "EVENT_AFTER_SESSION_END",
  UNKNOWN_EVENT_TYPE: "UNKNOWN_EVENT_TYPE",
  INVALID_PROGRESS_VALUE: "INVALID_PROGRESS_VALUE",
  INVALID_PAYLOAD_SHAPE: "INVALID_PAYLOAD_SHAPE",
} as const;

export type PopsEventDropReason = (typeof POPS_EVENT_DROP_REASONS)[keyof typeof POPS_EVENT_DROP_REASONS];
