import type { Dispute, POPSChallenge, VerificationGateResult, VerificationRecord } from "./studioVerificationTypes";

const t = (iso: string) => iso;

function gate(
  id: string,
  gateType: VerificationGateResult["gateType"],
  status: VerificationGateResult["status"],
  score: number,
  threshold: number,
  message: string,
  blocking: boolean
): VerificationGateResult {
  return {
    id,
    gateType,
    status,
    score,
    threshold,
    message,
    blocking,
    metadata: {},
    createdAt: t("2026-01-10T12:00:00.000Z"),
  };
}

export const mockVerificationRecords: VerificationRecord[] = [
  {
    id: "vr_pass_view",
    subjectType: "view",
    subjectId: "view_sess_demo",
    viewerAccountId: "acct_viewer",
    creatorAccountId: "acct_creator",
    postId: "post_demo",
    status: "passed",
    gates: [
      gate("g1", "watch_time", "passed", 0.92, 0.8, "Watch threshold met", true),
      gate("g2", "attention_score", "passed", 0.88, 0.7, "Attention stable", true),
      gate("g3", "human_presence", "passed", 1, 1, "Human presence (mock)", true),
    ],
    fraudScore: 12,
    trustImpact: [],
    settlementDecision: {
      status: "release_now",
      holdSeconds: 0,
      reason: "Low risk verified view",
    },
    createdAt: t("2026-01-10T12:00:00.000Z"),
    completedAt: t("2026-01-10T12:00:05.000Z"),
  },
  {
    id: "vr_farm_fail",
    subjectType: "campaign_action",
    subjectId: "camp_action_bad",
    viewerAccountId: "acct_viewer",
    campaignId: "camp_1",
    status: "failed",
    gates: [
      gate("g1", "velocity_check", "failed", 0.2, 0.5, "Too many actions in window", true),
      gate("g2", "duplicate_action", "failed", 0, 1, "Duplicate reward claim", true),
      gate("g3", "fraud_score", "failed", 82, 50, "Fraud score exceeded", true),
    ],
    fraudScore: 82,
    trustImpact: [],
    settlementDecision: {
      status: "reverse",
      holdSeconds: 0,
      reason: "Reward farming pattern",
    },
    createdAt: t("2026-01-11T09:00:00.000Z"),
    completedAt: t("2026-01-11T09:00:01.000Z"),
  },
  {
    id: "vr_magic_review",
    subjectType: "magic_unlock",
    subjectId: "unlock_pending",
    viewerAccountId: "acct_viewer",
    revealId: "reveal_pay",
    postId: "post_demo",
    status: "under_review",
    gates: [
      gate("g1", "payment_integrity", "passed", 1, 1, "Ledger debit matched", true),
      gate("g2", "content_safety", "warning", 0.6, 0.8, "Safety scan warning", false),
      gate("g3", "fraud_score", "warning", 48, 40, "Elevated fraud band", false),
    ],
    fraudScore: 48,
    trustImpact: [],
    settlementDecision: {
      status: "hold_pending",
      holdSeconds: 3600,
      reason: "Manual review queue (sim)",
      releaseAt: t("2026-01-11T10:00:00.000Z"),
    },
    createdAt: t("2026-01-11T08:30:00.000Z"),
  },
  {
    id: "vr_gps_fail",
    subjectType: "campaign_action",
    subjectId: "camp_checkin_1",
    viewerAccountId: "acct_viewer",
    campaignId: "camp_geo",
    status: "rejected",
    gates: [
      gate("g1", "location_proof", "failed", 0, 1, "GPS check-in mismatch (mock)", true),
      gate("g2", "session_integrity", "warning", 0.55, 0.7, "Session gap detected", false),
    ],
    fraudScore: 35,
    trustImpact: [],
    settlementDecision: {
      status: "block",
      holdSeconds: 0,
      reason: "Location campaign requires proof",
    },
    createdAt: t("2026-01-12T14:00:00.000Z"),
    completedAt: t("2026-01-12T14:00:02.000Z"),
  },
];

export const mockPOPSChallenges: POPSChallenge[] = [
  {
    id: "pops_tap_demo",
    method: "active_tap",
    prompt: "Tap the highlighted control within 8s",
    status: "shown",
    requiredWithinMs: 8000,
    score: 0,
    createdAt: t("2026-01-10T11:00:00.000Z"),
    metadata: {},
  },
  {
    id: "pops_hold_demo",
    method: "hold_gesture",
    prompt: "Press and hold for 2s",
    status: "idle",
    requiredWithinMs: 12_000,
    score: 0,
    createdAt: t("2026-01-10T11:05:00.000Z"),
    metadata: {},
  },
  {
    id: "pops_sess_demo",
    method: "session_continuity",
    prompt: "Keep this session active while earning",
    status: "passed",
    requiredWithinMs: 60_000,
    completedInMs: 22_000,
    score: 0.95,
    createdAt: t("2026-01-10T11:10:00.000Z"),
    completedAt: t("2026-01-10T11:10:22.000Z"),
    metadata: {},
  },
  {
    id: "pops_loc_demo",
    method: "location_presence",
    prompt: "Confirm you are at the campaign geofence (mock)",
    status: "failed",
    requiredWithinMs: 20_000,
    completedInMs: 19_000,
    score: 0.2,
    createdAt: t("2026-01-10T11:20:00.000Z"),
    completedAt: t("2026-01-10T11:20:19.000Z"),
    metadata: { locationMatch: false },
  },
];

export const mockDisputes: Dispute[] = [
  {
    id: "dsp_mislead",
    reason: "misleading_reveal",
    status: "open",
    reporterAccountId: "acct_viewer",
    creatorAccountId: "acct_creator",
    postId: "post_demo",
    revealId: "reveal_1",
    unlockId: "unlock_1",
    ledgerEntryIds: ["led_1"],
    evidence: [
      {
        id: "ev1",
        type: "user_statement",
        createdAt: t("2026-01-13T10:00:00.000Z"),
        payload: { text: "Reveal did not match description" },
      },
    ],
    trustImpacts: [],
    createdAt: t("2026-01-13T10:00:00.000Z"),
  },
  {
    id: "dsp_reward",
    reason: "reward_not_received",
    status: "under_review",
    reporterAccountId: "acct_viewer",
    creatorAccountId: "acct_creator",
    postId: "post_demo",
    campaignId: "camp_1",
    ledgerEntryIds: [],
    evidence: [],
    trustImpacts: [],
    createdAt: t("2026-01-13T11:00:00.000Z"),
  },
  {
    id: "dsp_camp_reject",
    reason: "campaign_action_rejected",
    status: "resolved_creator_wins",
    reporterAccountId: "acct_creator",
    postId: "post_demo",
    campaignId: "camp_2",
    ledgerEntryIds: ["led_2"],
    evidence: [],
    resolution: "Creator evidence accepted — action rejection upheld",
    trustImpacts: [],
    createdAt: t("2026-01-08T08:00:00.000Z"),
    resolvedAt: t("2026-01-09T15:00:00.000Z"),
  },
];

