export const POPS_FEATURE_FLAG = {
  ENABLE_POPS: "ENABLE_POPS",
  ENABLE_REWARD_DECISIONS: "ENABLE_REWARD_DECISIONS",
  ENABLE_WALLET_PENDING: "ENABLE_WALLET_PENDING",
  ENABLE_PRIVACY_RECEIPTS: "ENABLE_PRIVACY_RECEIPTS",
  ENABLE_TRUST_IMPACT: "ENABLE_TRUST_IMPACT",
  ENABLE_VISUAL_PRESENCE_LATER: "ENABLE_VISUAL_PRESENCE_LATER",
  ENABLE_STRICT_FRAUD_MODE: "ENABLE_STRICT_FRAUD_MODE",
  POPS_ENABLED: "POPS_ENABLED",
  POPS_FEED_TRACKING_ENABLED: "POPS_FEED_TRACKING_ENABLED",
  POPS_EARN_TRACKING_ENABLED: "POPS_EARN_TRACKING_ENABLED",
  POPS_REWARD_DECISIONS_ENABLED: "POPS_REWARD_DECISIONS_ENABLED",
  POPS_WALLET_PENDING_ENABLED: "POPS_WALLET_PENDING_ENABLED",
  POPS_TRUST_IMPACT_ENABLED: "POPS_TRUST_IMPACT_ENABLED",
  POPS_PRIVACY_RECEIPTS_ENABLED: "POPS_PRIVACY_RECEIPTS_ENABLED",
  POPS_VISUAL_PRESENCE_ENABLED: "POPS_VISUAL_PRESENCE_ENABLED",
  POPS_AUDIO_FEATURES_ENABLED: "POPS_AUDIO_FEATURES_ENABLED",
  POPS_EMOTION_INFERENCE_ENABLED: "POPS_EMOTION_INFERENCE_ENABLED",
  POPS_LOCATION_PROOF_ENABLED: "POPS_LOCATION_PROOF_ENABLED",
  POPS_RAW_MEDIA_STORAGE_ENABLED: "POPS_RAW_MEDIA_STORAGE_ENABLED",
  POPS_ADMIN_REVIEW_ENABLED: "POPS_ADMIN_REVIEW_ENABLED",
  POPS_DISPUTES_ENABLED: "POPS_DISPUTES_ENABLED",
  POPS_HIGH_VALUE_HOLDS_ENABLED: "POPS_HIGH_VALUE_HOLDS_ENABLED",
  POPS_STRICT_FRAUD_MODE_ENABLED: "POPS_STRICT_FRAUD_MODE_ENABLED",
  POPS_CREATOR_ANALYTICS_ENABLED: "POPS_CREATOR_ANALYTICS_ENABLED",
  POPS_BRAND_ANALYTICS_ENABLED: "POPS_BRAND_ANALYTICS_ENABLED"
} as const;

export type PopsFeatureFlag = (typeof POPS_FEATURE_FLAG)[keyof typeof POPS_FEATURE_FLAG];

export type PopsFeatureFlagState = Record<PopsFeatureFlag, boolean>;

export const POPS_ALL_FEATURE_FLAGS: PopsFeatureFlag[] = Object.values(POPS_FEATURE_FLAG);

export function createDefaultFeatureFlags(value: boolean = false): PopsFeatureFlagState {
  return POPS_ALL_FEATURE_FLAGS.reduce<PopsFeatureFlagState>((acc, flag) => {
    acc[flag] = value;
    return acc;
  }, {} as PopsFeatureFlagState);
}
