import { POPS_TRUST_EVENT_TYPE, type PopsTrustEventType } from "./pops-trust.types";

const POSITIVE_TRUST_EVENT_TYPES = new Set<PopsTrustEventType>([
  POPS_TRUST_EVENT_TYPE.VERIFIED_HUMAN_MOMENT,
  POPS_TRUST_EVENT_TYPE.VERIFIED_ATTENTION_SESSION,
  POPS_TRUST_EVENT_TYPE.VERIFIED_INTENT_ACTION,
  POPS_TRUST_EVENT_TYPE.CLEAN_REWARD_COMPLETION,
  POPS_TRUST_EVENT_TYPE.CLEAN_CAMPAIGN_COMPLETION,
  POPS_TRUST_EVENT_TYPE.CONSISTENT_DEVICE_PRESENCE,
  POPS_TRUST_EVENT_TYPE.CONSISTENT_ACCOUNT_CONTINUITY,
  POPS_TRUST_EVENT_TYPE.CLEAN_PAYOUT_BEHAVIOR
]);

const NEGATIVE_TRUST_EVENT_TYPES = new Set<PopsTrustEventType>([
  POPS_TRUST_EVENT_TYPE.LOW_CONFIDENCE_SESSION,
  POPS_TRUST_EVENT_TYPE.REPEATED_DEGRADED_SESSION,
  POPS_TRUST_EVENT_TYPE.SUSPICIOUS_AUTOMATION_PATTERN,
  POPS_TRUST_EVENT_TYPE.IMPOSSIBLE_PROGRESS_PATTERN,
  POPS_TRUST_EVENT_TYPE.DEVICE_INTEGRITY_WARNING,
  POPS_TRUST_EVENT_TYPE.DUPLICATE_REWARD_ATTEMPT,
  POPS_TRUST_EVENT_TYPE.HIGH_FRAUD_RISK_SESSION,
  POPS_TRUST_EVENT_TYPE.IDENTITY_CONTINUITY_BREAK,
  POPS_TRUST_EVENT_TYPE.REWARD_ABUSE_PATTERN
]);

export function isPositiveTrustEventType(eventType: PopsTrustEventType): boolean {
  return POSITIVE_TRUST_EVENT_TYPES.has(eventType);
}

export function isNegativeTrustEventType(eventType: PopsTrustEventType): boolean {
  return NEGATIVE_TRUST_EVENT_TYPES.has(eventType);
}
