import express from "express";
import { errorHandler } from "./middleware/error-handler";
import { adminCorrectiveActionRouter } from "./modules/admin-corrective-action/admin-corrective-action.routes";
import { requestIdMiddleware } from "./middleware/request-id";
import { adminIncidentReviewRouter } from "./modules/admin-incident-review/admin-incident-review.routes";
import { adminMfaRouter } from "./modules/admin-mfa/admin-mfa.routes";
import { adminSecurityCenterRouter } from "./modules/admin-security-center/admin-security-center.routes";
import { adminSecurityDeletionRouter } from "./modules/admin-security-deletion/admin-security-deletion.routes";
import { adminSecurityGovernanceRouter } from "./modules/admin-security-governance/admin-security-governance.routes";
import { adminSecurityPolicyChangeRouter } from "./modules/admin-security-policy-change/admin-security-policy-change.routes";
import { adminSecurityControlsRouter } from "./modules/admin-security-controls/admin-security-controls.routes";
import { adminSecurityReportsRouter } from "./modules/admin-security-reports/admin-security-reports.routes";
import { adminSecurityAuditorsRouter } from "./modules/admin-security-auditors/admin-security-auditors.routes";
import { adminRouter } from "./modules/admin/admin.routes";
import { adminBreakGlassRouter } from "./modules/admin-break-glass/admin-break-glass.routes";
import { adminSecurityArchiveRouter } from "./modules/admin-security-archive/admin-security-archive.routes";
import { adminSecurityLegalHoldRouter } from "./modules/admin-security-legal-hold/admin-security-legal-hold.routes";
import { adminSecurityNotificationsRouter } from "./modules/admin-security-notifications/admin-security-notifications.routes";
import { adminSecurityAuditPeriodsRouter } from "./modules/admin-security-audit-periods/admin-security-audit-periods.routes";
import { adminSecurityComplianceReportsRouter } from "./modules/admin-security-compliance-reports/admin-security-compliance-reports.routes";
import { adminSecurityQuestionnairesRouter } from "./modules/admin-security-questionnaires/admin-security-questionnaires.routes";
import { adminSecurityRevocationsRouter } from "./modules/admin-security-revocations/admin-security-revocations.routes";
import { adminSecurityDisclosureApprovalsRouter } from "./modules/admin-security-disclosure-approvals/admin-security-disclosure-approvals.routes";
import { adminSecurityDisclosurePackagesRouter } from "./modules/admin-security-disclosure-packages/admin-security-disclosure-packages.routes";
import { publicComplianceVerificationRouter } from "./modules/public-compliance-verification/public-compliance-verification.routes";
import { publicTrustTimelineRouter } from "./modules/public-trust-timeline/public-trust-timeline.routes";
import { adminSecurityEnterpriseReviewRoomsRouter } from "./modules/admin-security-enterprise-review-rooms/admin-security-enterprise-review-rooms.routes";
import { adminSecurityTrustTimelineRouter } from "./modules/admin-security-trust-timeline/admin-security-trust-timeline.routes";
import { adminSecurityTrustTimelineCryptoRouter } from "./modules/admin-security-trust-timeline-crypto/admin-security-trust-timeline-crypto.routes";
import { adminSecurityAuditorPortalsRouter } from "./modules/admin-security-auditor-portals/admin-security-auditor-portals.routes";
import { adminSecurityTrustDependenciesRouter } from "./modules/admin-security-trust-dependencies/admin-security-trust-dependencies.routes";
import { adminSecurityRetentionRouter } from "./modules/admin-security-retention/admin-security-retention.routes";
import { adminSecurityTrustNotificationsRouter } from "./modules/admin-security-trust-notifications/admin-security-trust-notifications.routes";
import { adminSecurityTrustCenterRouter } from "./modules/admin-security-trust-center/admin-security-trust-center.routes";
import { attentionRouter } from "./modules/attention/attention.routes";
import { meRouter } from "./modules/me/me.routes";
import { riskRouter } from "./modules/risk/risk.routes";
import { rewardsRouter } from "./modules/rewards/rewards.routes";
import { withdrawalsRouter } from "./modules/withdrawals/withdrawals.routes";
import { walletRouter } from "./modules/wallet/wallet.routes";
import { webhooksRouter } from "./modules/webhooks/webhooks.routes";
import { workerRouter } from "./modules/worker/worker.routes";
import { auditorPortalRouter } from "./modules/auditor-portal/auditor-portal.routes";
import { enterpriseReviewRoomRouter } from "./modules/enterprise-review-room/enterprise-review-room.routes";
import { publicTrustCenterRouter } from "./modules/public-trust-center/public-trust-center.routes";
import { adminSecurityDownloadsRouter } from "./modules/admin-security-downloads/admin-security-downloads.routes";
import { artifactDownloadsRouter } from "./modules/artifact-downloads/artifact-downloads.routes";
import { adminSecurityArtifactViewerRouter } from "./modules/admin-security-artifact-viewer/admin-security-artifact-viewer.routes";
import { adminSecurityArtifactSearchRouter } from "./modules/admin-security-artifact-search/admin-security-artifact-search.routes";
import { artifactSearchRouter } from "./modules/artifact-search/artifact-search.routes";
import { artifactViewerRouter } from "./modules/artifact-viewer/artifact-viewer.routes";
import { adminSecurityEvidenceAnswersRouter } from "./modules/admin-security-evidence-answers/admin-security-evidence-answers.routes";
import { evidenceAnswersRouter } from "./modules/evidence-answers/evidence-answers.routes";
import { adminSecurityAnswerReceiptsRouter } from "./modules/admin-security-answer-receipts/admin-security-answer-receipts.routes";
import { answerReceiptsRouter } from "./modules/answer-receipts/answer-receipts.routes";
import { adminSecurityAnswerReceiptExportsRouter } from "./modules/admin-security-answer-receipt-exports/admin-security-answer-receipt-exports.routes";
import { answerReceiptExportsRouter } from "./modules/answer-receipt-exports/answer-receipt-exports.routes";
import { trustTimelineRouter } from "./modules/trust-timeline/trust-timeline.routes";
import { adminSecurityTrustProofReportsRouter } from "./modules/admin-security-trust-proof-reports/admin-security-trust-proof-reports.routes";
import { trustProofReportsRouter } from "./modules/trust-proof-reports/trust-proof-reports.routes";
import { adminSecurityCustomerTrustProofPortalsRouter } from "./modules/admin-security-customer-trust-proof-portals/admin-security-customer-trust-proof-portals.routes";
import { customerTrustProofPortalRouter } from "./modules/customer-trust-proof-portal/customer-trust-proof-portal.routes";
import { adminSecurityProofQrRouter } from "./modules/admin-security-proof-qr/admin-security-proof-qr.routes";
import { adminSecurityProofDigestsRouter } from "./modules/admin-security-proof-digests/admin-security-proof-digests.routes";
import { adminSecurityProofObservabilityRouter } from "./modules/admin-security-proof-observability/admin-security-proof-observability.routes";
import { adminSecurityAuditPackagesRouter } from "./modules/admin-security-audit-packages/admin-security-audit-packages.routes";
import { adminSecurityTrustTransparencyRouter } from "./modules/admin-security-trust-transparency/admin-security-trust-transparency.routes";
import { adminSecurityTrustBillingRouter } from "./modules/admin-security-trust-billing/admin-security-trust-billing.routes";
import { adminSecurityTrustAiAnalystRouter } from "./modules/admin-security-trust-ai-analyst/admin-security-trust-ai-analyst.routes";
import { adminSecurityTrustCommandCenterRouter } from "./modules/admin-security-trust-command-center/admin-security-trust-command-center.routes";
import { adminSecurityTrustAlertsRouter } from "./modules/admin-security-trust-alerts/admin-security-trust-alerts.routes";
import { auditPackageAccessRouter } from "./modules/audit-package-access/audit-package-access.routes";
import { proofLinksRouter } from "./modules/proof-links/proof-links.routes";
import { proofQrRouter } from "./modules/proof-qr/proof-qr.routes";
import { proofDigestsRouter } from "./modules/proof-digests/proof-digests.routes";
import { trustTransparencyRouter } from "./modules/trust-transparency/trust-transparency.routes";
import { popsSessionRouter } from "./server/pops/routes/pops-session.routes";
import { popsEventRouter } from "./server/pops/routes/pops-event.routes";
import { alphabetActionsRouter } from "./modules/alphabet-actions/alphabet-actions.routes";
import { adminReviewCasesRouter } from "./modules/admin-review-cases/admin-review-cases.routes";
import { alphabetProviderReconciliationWebhookRouter } from "./modules/webhooks/alphabet-provider-reconciliation.routes";
import { adminSystemTimelineRouter } from "./modules/admin-system-timeline/admin-system-timeline.routes";
import { cronAlphabetRouter } from "./modules/cron-alphabet/cron-alphabet.routes";
import { adminScheduledJobsRouter } from "./modules/admin-scheduled-jobs/admin-scheduled-jobs.routes";
import { adminTrustFraudReviewRouter } from "./modules/admin-trust-fraud-review/admin-trust-fraud-review.routes";

export function createApp() {
  const app = express();

  app.use("/v1/webhooks/alphabet/provider", alphabetProviderReconciliationWebhookRouter);
  app.use("/v1/cron/alphabet", cronAlphabetRouter);
  app.use(express.json({ limit: "64kb" }));
  app.use(requestIdMiddleware);

  app.get("/health", (_req, res) => {
    res.json({
      ok: true,
      status: "healthy"
    });
  });

  app.use("/v1/wallet", walletRouter);
  app.use("/v1/attention", attentionRouter);
  app.use("/v1/rewards", rewardsRouter);
  app.use("/v1/risk", riskRouter);
  app.use("/v1/withdrawals", withdrawalsRouter);
  app.use("/v1/webhooks", webhooksRouter);
  app.use("/v1/me", meRouter);
  app.use("/v1/worker", workerRouter);
  app.use("/v1/admin/system-timeline", adminSystemTimelineRouter);
  app.use("/v1/admin/scheduled-jobs", adminScheduledJobsRouter);
  app.use("/v1/admin/alphabet/trust-fraud-review", adminTrustFraudReviewRouter);
  app.use("/v1/admin", adminRouter);
  app.use("/v1/admin/mfa", adminMfaRouter);
  app.use("/v1/admin/security-center", adminSecurityCenterRouter);
  app.use("/v1/admin/security-deletion", adminSecurityDeletionRouter);
  app.use("/v1/admin/security-governance", adminSecurityGovernanceRouter);
  app.use("/v1/admin/security-policy-changes", adminSecurityPolicyChangeRouter);
  app.use("/v1/admin/security-controls", adminSecurityControlsRouter);
  app.use("/v1/admin/security-auditors", adminSecurityAuditorsRouter);
  app.use("/v1/admin/security-reports", adminSecurityReportsRouter);
  app.use("/v1/admin/security-archive", adminSecurityArchiveRouter);
  app.use("/v1/admin/security-legal-holds", adminSecurityLegalHoldRouter);
  app.use("/v1/admin/incident-reviews", adminIncidentReviewRouter);
  app.use("/v1/admin/alphabet/review-cases", adminReviewCasesRouter);
  app.use("/v1/admin/corrective-actions", adminCorrectiveActionRouter);
  app.use("/v1/admin/break-glass", adminBreakGlassRouter);
  app.use("/v1/admin/security-notifications", adminSecurityNotificationsRouter);
  app.use("/v1/admin/security-audit-periods", adminSecurityAuditPeriodsRouter);
  app.use("/v1/admin/security-compliance-reports", adminSecurityComplianceReportsRouter);
  app.use("/v1/admin/security-questionnaires", adminSecurityQuestionnairesRouter);
  app.use("/v1/admin/security-revocations", adminSecurityRevocationsRouter);
  app.use("/v1/admin/security-disclosure-approvals", adminSecurityDisclosureApprovalsRouter);
  app.use("/v1/admin/security-disclosure-packages", adminSecurityDisclosurePackagesRouter);
  app.use("/v1/admin/security-trust-timeline", adminSecurityTrustTimelineRouter);
  app.use("/v1/admin/security-trust-timeline-crypto", adminSecurityTrustTimelineCryptoRouter);
  app.use("/v1/admin/security-enterprise-review-rooms", adminSecurityEnterpriseReviewRoomsRouter);
  app.use("/v1/admin/security-auditor-portals", adminSecurityAuditorPortalsRouter);
  app.use("/v1/admin/security-trust-dependencies", adminSecurityTrustDependenciesRouter);
  app.use("/v1/admin/security-retention", adminSecurityRetentionRouter);
  app.use("/v1/admin/security-trust-notifications", adminSecurityTrustNotificationsRouter);
  app.use("/v1/admin/security-trust-center", adminSecurityTrustCenterRouter);
  app.use("/v1/admin/security-downloads", adminSecurityDownloadsRouter);
  app.use("/v1/admin/security-artifact-viewer", adminSecurityArtifactViewerRouter);
  app.use("/v1/admin/security-evidence-answers", adminSecurityEvidenceAnswersRouter);
  app.use("/v1/admin/security-answer-receipts", adminSecurityAnswerReceiptsRouter);
  app.use("/v1/admin/security-answer-receipt-exports", adminSecurityAnswerReceiptExportsRouter);
  app.use("/v1/admin/security-artifact-search", adminSecurityArtifactSearchRouter);
  app.use("/v1/admin/security-trust-proof-reports", adminSecurityTrustProofReportsRouter);
  app.use("/v1/admin/security-customer-trust-proof-portals", adminSecurityCustomerTrustProofPortalsRouter);
  app.use("/v1/admin/security-proof-qr", adminSecurityProofQrRouter);
  app.use("/v1/admin/security-proof-digests", adminSecurityProofDigestsRouter);
  app.use("/v1/admin/security-proof-observability", adminSecurityProofObservabilityRouter);
  app.use("/v1/admin/security-audit-packages", adminSecurityAuditPackagesRouter);
  app.use("/v1/admin/security-trust-transparency", adminSecurityTrustTransparencyRouter);
  app.use("/v1/admin/security-trust-billing", adminSecurityTrustBillingRouter);
  app.use("/v1/admin/security-trust-ai-analyst", adminSecurityTrustAiAnalystRouter);
  app.use("/v1/admin/security-trust-command-center", adminSecurityTrustCommandCenterRouter);
  app.use("/v1/admin/security-trust-alerts", adminSecurityTrustAlertsRouter);
  app.use("/v1/public", publicComplianceVerificationRouter);
  app.use("/v1/public", publicTrustTimelineRouter);
  app.use("/v1/public/trust-center", publicTrustCenterRouter);
  app.use("/v1/auditor", auditorPortalRouter);
  app.use("/v1/auditor-portals", auditorPortalRouter);
  app.use("/v1/enterprise-review-rooms", enterpriseReviewRoomRouter);
  app.use("/v1/artifact-downloads", artifactDownloadsRouter);
  app.use("/v1/artifact-viewer", artifactViewerRouter);
  app.use("/v1/evidence-answers", evidenceAnswersRouter);
  app.use("/v1/answer-receipts", answerReceiptsRouter);
  app.use("/v1/answer-receipt-exports", answerReceiptExportsRouter);
  app.use("/v1/artifact-search", artifactSearchRouter);
  app.use("/v1/trust-timeline", trustTimelineRouter);
  app.use("/v1/trust-proof-reports", trustProofReportsRouter);
  app.use("/v1/customer-trust-proof-portal", customerTrustProofPortalRouter);
  app.use("/v1/proof-links", proofLinksRouter);
  app.use("/v1/proof-qr", proofQrRouter);
  app.use("/v1/proof-digests", proofDigestsRouter);
  app.use("/v1/audit-package-access", auditPackageAccessRouter);
  app.use("/v1/trust-transparency", trustTransparencyRouter);
  app.use("/api/pops", popsSessionRouter);
  app.use("/api/pops", popsEventRouter);
  app.use("/api", alphabetActionsRouter);

  app.use(errorHandler);

  return app;
}
