"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.POPS_CAMPAIGN_PROOF_PRESET = exports.POPS_MANUAL_REVIEW_POLICY = exports.POPS_REWARD_HOLD_POLICY = exports.POPS_PROOF_LEVEL = void 0;
exports.POPS_PROOF_LEVEL = {
    LEVEL_1_SESSION: "LEVEL_1_SESSION",
    LEVEL_2_ATTENTION: "LEVEL_2_ATTENTION",
    LEVEL_3_INTENT: "LEVEL_3_INTENT",
    LEVEL_4_IDENTITY_CONTINUITY: "LEVEL_4_IDENTITY_CONTINUITY",
    LEVEL_5_HIGH_VALUE: "LEVEL_5_HIGH_VALUE"
};
exports.POPS_REWARD_HOLD_POLICY = {
    RELEASE_IMMEDIATE: "RELEASE_IMMEDIATE",
    HOLD_UNTIL_VERIFIED: "HOLD_UNTIL_VERIFIED",
    HOLD_24H: "HOLD_24H",
    HOLD_72H: "HOLD_72H",
    MANUAL_RELEASE: "MANUAL_RELEASE"
};
exports.POPS_MANUAL_REVIEW_POLICY = {
    DISABLED: "DISABLED",
    CONDITIONAL: "CONDITIONAL",
    ENABLED: "ENABLED"
};
exports.POPS_CAMPAIGN_PROOF_PRESET = {
    BASIC_VIEW: "BASIC_VIEW",
    PAID_WATCH: "PAID_WATCH",
    CTA_INTENT: "CTA_INTENT",
    LOCAL_VISIT: "LOCAL_VISIT",
    HIGH_VALUE_REWARD: "HIGH_VALUE_REWARD"
};
