import { z } from "zod";

export const workerJobKeySchema = z.enum([
  "reward_issuance_every_minute",
  "reward_release_every_5_minutes",
  "accounting_mirror_every_minute",
  "audit_hash_backfill_hourly",
  "audit_hash_verify_daily",
  "observability_snapshot_every_5_minutes",
  "admin_security_alert_provider_delivery_every_minute",
  "admin_security_notifications_delivery",
  "admin_security_trust_notification_delivery",
  "admin_security_archive_export_delivery",
  "admin_security_auditor_export_generation",
  "admin_security_auditor_packet_manifest_generation",
  "admin_security_audit_period_export_generation",
  "admin_security_questionnaire_ai_drafting",
  "admin_security_audit_period_exports_expire_hourly",
  "admin_security_disclosure_approval_expire_hourly",
  "admin_security_enterprise_review_rooms_expire_hourly",
  "admin_security_archive_exports_enqueue_hourly",
  "admin_security_archive_verification_delivery",
  "admin_security_archive_verifications_enqueue_hourly",
  "admin_security_legal_holds_expire_hourly",
  "admin_security_alert_escalation_every_5_minutes",
  "admin_security_daily_snapshot_every_day",
  "admin_incident_corrective_actions_overdue_every_15_minutes",
  "admin_security_auditors_expire_hourly",
  "admin_security_retention_discovery_daily",
  "admin_security_retention_lifecycle_daily",
  "admin_security_trust_notification_fanout_every_5m",
  "admin_security_trust_expiry_warnings_daily",
  "admin_security_trust_dependency_discovery_hourly",
  "admin_security_trust_dependency_propagation_every_5m",
  "admin_security_trust_center_manifest_refresh_hourly",
  "admin_security_artifact_download_subject_discovery_hourly",
  "admin_security_artifact_download_grant_expiry_every_5m",
  "admin_security_artifact_viewer_subject_discovery_hourly",
  "admin_security_artifact_viewer_session_expiry_every_5m",
  "admin_security_artifact_search_document_discovery_hourly",
  "admin_security_artifact_search_session_expiry_every_5m",
  "admin_security_evidence_answer_session_expiry_every_5m",
  "admin_security_answer_receipt_expiry_every_5m",
  "admin_security_answer_receipt_signing",
  "admin_security_artifact_search_indexing",
  "admin_security_trust_timeline_chain_events_every_5m",
  "admin_security_trust_timeline_discovery_every_5m",
  "admin_security_trust_timeline_snapshot_expiry_every_5m",
  "customer_trust_proof_portal_session_expiry_every_5m",
  "admin_security_trust_proof_report_expiry_every_5m",
  "admin_security_trust_proof_report_build",
  "admin_security_proof_qr_code_build",
  "admin_security_proof_verification_link_expiry_every_5m",
  "admin_security_proof_digest_process_every_15m",
  "admin_security_proof_notification_event_expiry_daily",
  "admin_security_proof_observability_cycle_every_5m",
  "admin_security_proof_observability_expiry_daily",
  "admin_security_audit_package_process_every_15m",
  "admin_security_audit_package_expiry_daily",
  "admin_security_trust_transparency_process_every_15m",
  "admin_security_trust_transparency_expiry_daily",
  "admin_security_trust_billing_cycle_hourly",
  "admin_security_trust_usage_rollups_every_15m",
  "admin_security_trust_ai_analyst_every_15m",
  "admin_security_customer_trust_risk_scores_hourly",
  "admin_security_trust_command_center_global_every_5m",
  "admin_security_trust_command_center_customers_every_30m",
  "admin_security_trust_alert_sync_every_minute",
  "admin_security_trust_alert_build_notifications_every_minute",
  "admin_security_trust_alert_lease_notifications_every_minute",
  "admin_security_trust_alert_escalate_every_5m"
]);

export const runWorkerJobSchema = z.object({
  jobKey: workerJobKeySchema,
  lockedBy: z.string().min(1).optional(),
  metadata: z.record(z.unknown()).optional()
});

export type RunWorkerJobResponseDto = {
  scheduledJobRunId: string;
};
