import { POPS_SESSION_STATE, type PopsSessionState } from "../types/pops.types";

export const POPS_STATE_TRANSITIONS: Record<PopsSessionState, PopsSessionState[]> = {
  [POPS_SESSION_STATE.NOT_STARTED]: [POPS_SESSION_STATE.INITIALIZING],
  [POPS_SESSION_STATE.INITIALIZING]: [
    POPS_SESSION_STATE.DETECTING,
    POPS_SESSION_STATE.UNCERTAIN,
    POPS_SESSION_STATE.DEGRADED,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.DETECTING]: [
    POPS_SESSION_STATE.PRESENT_IDLE,
    POPS_SESSION_STATE.ENGAGED_PASSIVE,
    POPS_SESSION_STATE.UNCERTAIN,
    POPS_SESSION_STATE.DEGRADED,
    POPS_SESSION_STATE.INTERRUPTED,
    POPS_SESSION_STATE.SUSPICIOUS,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.PRESENT_IDLE]: [
    POPS_SESSION_STATE.ENGAGED_PASSIVE,
    POPS_SESSION_STATE.ENGAGED_ACTIVE,
    POPS_SESSION_STATE.DISTRACTED,
    POPS_SESSION_STATE.INTERRUPTED,
    POPS_SESSION_STATE.DEGRADED,
    POPS_SESSION_STATE.SUSPICIOUS,
    POPS_SESSION_STATE.COMPLETED,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.ENGAGED_PASSIVE]: [
    POPS_SESSION_STATE.ENGAGED_ACTIVE,
    POPS_SESSION_STATE.FOCUSED,
    POPS_SESSION_STATE.DISTRACTED,
    POPS_SESSION_STATE.INTERRUPTED,
    POPS_SESSION_STATE.DEGRADED,
    POPS_SESSION_STATE.SUSPICIOUS,
    POPS_SESSION_STATE.COMPLETED,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.ENGAGED_ACTIVE]: [
    POPS_SESSION_STATE.FOCUSED,
    POPS_SESSION_STATE.ENGAGED_PASSIVE,
    POPS_SESSION_STATE.DISTRACTED,
    POPS_SESSION_STATE.INTERRUPTED,
    POPS_SESSION_STATE.DEGRADED,
    POPS_SESSION_STATE.SUSPICIOUS,
    POPS_SESSION_STATE.COMPLETED,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.FOCUSED]: [
    POPS_SESSION_STATE.ENGAGED_ACTIVE,
    POPS_SESSION_STATE.DISTRACTED,
    POPS_SESSION_STATE.INTERRUPTED,
    POPS_SESSION_STATE.SUSPICIOUS,
    POPS_SESSION_STATE.COMPLETED,
    POPS_SESSION_STATE.REWARD_PENDING,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.DISTRACTED]: [
    POPS_SESSION_STATE.PRESENT_IDLE,
    POPS_SESSION_STATE.ENGAGED_PASSIVE,
    POPS_SESSION_STATE.ENGAGED_ACTIVE,
    POPS_SESSION_STATE.FOCUSED,
    POPS_SESSION_STATE.INTERRUPTED,
    POPS_SESSION_STATE.DEGRADED,
    POPS_SESSION_STATE.SUSPICIOUS,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.INTERRUPTED]: [
    POPS_SESSION_STATE.DETECTING,
    POPS_SESSION_STATE.PRESENT_IDLE,
    POPS_SESSION_STATE.UNCERTAIN,
    POPS_SESSION_STATE.DEGRADED,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.DEGRADED]: [
    POPS_SESSION_STATE.DETECTING,
    POPS_SESSION_STATE.UNCERTAIN,
    POPS_SESSION_STATE.SUSPICIOUS,
    POPS_SESSION_STATE.INTERRUPTED,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.UNCERTAIN]: [
    POPS_SESSION_STATE.DETECTING,
    POPS_SESSION_STATE.PRESENT_IDLE,
    POPS_SESSION_STATE.DEGRADED,
    POPS_SESSION_STATE.SUSPICIOUS,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.SUSPICIOUS]: [
    POPS_SESSION_STATE.DEGRADED,
    POPS_SESSION_STATE.FRAUD_LIKELY,
    POPS_SESSION_STATE.REWARD_PENDING,
    POPS_SESSION_STATE.REWARD_DENIED,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.FRAUD_LIKELY]: [
    POPS_SESSION_STATE.REWARD_DENIED,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.COMPLETED]: [
    POPS_SESSION_STATE.REWARD_PENDING,
    POPS_SESSION_STATE.REWARD_APPROVED,
    POPS_SESSION_STATE.REWARD_PARTIAL,
    POPS_SESSION_STATE.REWARD_DENIED,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.REWARD_PENDING]: [
    POPS_SESSION_STATE.REWARD_APPROVED,
    POPS_SESSION_STATE.REWARD_PARTIAL,
    POPS_SESSION_STATE.REWARD_DENIED,
    POPS_SESSION_STATE.CLOSED
  ],
  [POPS_SESSION_STATE.REWARD_APPROVED]: [POPS_SESSION_STATE.CLOSED],
  [POPS_SESSION_STATE.REWARD_PARTIAL]: [POPS_SESSION_STATE.CLOSED],
  [POPS_SESSION_STATE.REWARD_DENIED]: [POPS_SESSION_STATE.CLOSED],
  [POPS_SESSION_STATE.CLOSED]: []
};

export function canTransitionPopsSessionState(
  from: PopsSessionState,
  to: PopsSessionState
): boolean {
  return POPS_STATE_TRANSITIONS[from].includes(to);
}
